name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Your other build steps here
      # - name: Run tests, build, etc.

     # This 'always()' block runs the email step even if previous steps fail.
      - name: Send email on failure
        if: failure() # Executes only on workflow failure
        uses: dawidd6/action-send-mail@v3
        with:
         server_address: smtp.example.com
         server_port: 587
         username: ${{ secrets.EMAIL_USERNAME }}
         password: ${{ secrets.EMAIL_PASSWORD }}
         subject: GitHub Action Failed, action is needed
         to: jitendra.ksh@gmail.com
         from: noreply@gmail.com
         body: |
          The workflow for the commit ${{ github.sha }} failed. Please review.
