name: Manual Prompt Example

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'staging'

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Use input value
        run: |
          echo "You selected environment: ${{ github.event.inputs.environment }}"
