name: Run CLI Commands

on:
  push:
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-cli:
    name: Run Commands
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run simple shell commands
        run: |
          echo "✅ Running command-line operations"
          pwd
          ls -al
          echo "🔧 Current date:"
          date
          echo "✅ Done"
